Fix BrightcoveVideo style removal
ExtensionEngine/tailor-teaching-elements pull request #77
Opened 2020-02-11 09:45 UTC by vkaracic

When there are multiple instances of the BrightcoveVideo teaching
element with the same playerId each of them would try to remove the same
<style> DOM node which is removed by the first instance causing errors
for all the rest of them. To fix this checks are added to verify the DOM
node exists before trying to remove it.

2020-02-12 02:16 UTC, vladimyr requested changes
Regardless of those comments you did very nice investigation 👍

2020-02-12 02:16 UTC, vladimyr commented on src/teaching-element/BrightcoveVideo.vue
> +        script = null;
Once destructured all further changes that are made on it won't be reflected on source object.

2020-02-12 02:16 UTC, vladimyr commented on src/teaching-element/BrightcoveVideo.vue
> +        style = null;
Same as above.

2020-02-12 07:54 UTC, vkaracic commented
@vladimyr thanks for the review. There is also a similar issue with multiple script tags in the same scenario, where they would point to the same script, but unfortunately I currently don't have time to fix that (should I file an issue for that here?)

To whoever is going to merge this: please squash commits before merging.

2020-02-19 00:05 UTC, vladimyr commented
> @vladimyr thanks for the review. There is also a similar issue with multiple script tags in the same scenario, where they would point to the same script, but unfortunately I currently don't have time to fix that (should I file an issue for that here?)

I'll try to do something about it before we merge it.

2020-02-19 00:05 UTC, vladimyr approved these changes

2020-02-19 11:17 UTC, abasic approved these changes

2020-02-26 09:03 UTC, vkaracic commented
@vladimyr as part of this PR or?

2020-02-26 14:30 UTC, vladimyr commented
Yup 😉

2020-09-29 08:59 UTC, vkaracic commented
Closing in favor of https://github.com/ExtensionEngine/tailor-teaching-elements/pull/93

2020-09-29 08:59 UTC, closed without merging